// Code generated by Slice Machine. DO NOT EDIT.

import FirstPage from './FirstPage/index.svelte';
import RichText from './RichText/index.svelte';
import SecondPage from './SecondPage/index.svelte';

export const components = {
	first_page: FirstPage,
	rich_text: RichText,
	second_page: SecondPage
};
